# Generated by Django 4.2.7 on 2025-09-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificatServicesConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition1', models.CharField(max_length=100)),
                ('condition2', models.CharField(max_length=100)),
                ('condition3', models.CharField(max_length=100)),
                ('condition4', models.CharField(max_length=100)),
            ],
        ),
    ]
