# Generated by Django 4.2.7 on 2025-09-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0002_certificatservicesconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatservicesconditions',
            name='condition1',
            field=models.BooleanField(default=False, verbose_name='足立区に住民登録がある'),
        ),
        migrations.AlterField(
            model_name='certificatservicesconditions',
            name='condition2',
            field=models.BooleanField(default=False, verbose_name='足立区に印鑑登録している'),
        ),
        migrations.AlterField(
            model_name='certificatservicesconditions',
            name='condition3',
            field=models.BooleanField(default=False, verbose_name='本籍が足立区にある'),
        ),
        migrations.AlterField(
            model_name='certificatservicesconditions',
            name='condition4',
            field=models.BooleanField(default=False, verbose_name='今年度1月1日時点で足立区に住民登録'),
        ),
    ]
