# Generated by Django 4.2.7 on 2025-09-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0003_alter_certificatservicesconditions_condition1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewCertificatServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100)),
                ('condition1', models.BooleanField(default=False, verbose_name='足立区に住民登録がある')),
                ('condition2', models.BooleanField(default=False, verbose_name='足立区に印鑑登録している')),
                ('condition3', models.BooleanField(default=False, verbose_name='本籍が足立区にある')),
                ('condition4', models.BooleanField(default=False, verbose_name='今年度1月1日時点で足立区に住民登録')),
            ],
        ),
    ]
