# Generated by Django 4.2.7 on 2025-09-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0004_viewcertificatservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewCertificatServicesMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('wardOfficePossiblke', models.BooleanField(verbose_name=False)),
                ('wardOfficeDocument', models.CharField(max_length=100)),
                ('combinancePossible', models.BooleanField(verbose_name=False)),
                ('combinanceDocument', models.CharField(max_length=100)),
                ('mailPossible', models.BooleanField(verbose_name=False)),
                ('mailDocument', models.CharField(max_length=100)),
                ('supplement', models.CharField(max_length=100)),
            ],
        ),
    ]
