# Generated by Django 4.2.7 on 2025-09-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0005_viewcertificatservicesmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcertificatservicesmethod',
            old_name='wardOfficePossiblke',
            new_name='wardOfficePossible',
        ),
    ]
