# Generated by Django 4.2.7 on 2025-09-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0006_rename_wardofficepossiblke_viewcertificatservicesmethod_wardofficepossible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcertificatservicesmethod',
            old_name='combinanceDocument',
            new_name='convenienceDocument',
        ),
        migrations.RenameField(
            model_name='viewcertificatservicesmethod',
            old_name='combinancePossible',
            new_name='conveniencePossible',
        ),
    ]
