# Generated by Django 4.2.7 on 2025-09-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0007_rename_combinancedocument_viewcertificatservicesmethod_conveniencedocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcertificatservicesmethod',
            name='supplement',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
