# Generated by Django 4.2.7 on 2025-09-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0008_alter_viewcertificatservicesmethod_supplement'),
    ]

    operations = [
        migrations.CreateModel(
            name='kidsServicessConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100)),
                ('windows', models.CharField(max_length=100)),
                ('mailAble', models.BooleanField(default=False)),
                ('conditionAble', models.BooleanField(default=False)),
                ('conditionLimit', models.IntegerField(blank=True)),
                ('conditionReference', models.IntegerField(blank=True)),
                ('conditionAdd', models.IntegerField(blank=True)),
            ],
        ),
    ]
