# Generated by Django 4.2.7 on 2025-09-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0009_kidsservicessconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidsservicessconditions',
            name='conditionAble',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
