# Generated by Django 4.2.7 on 2025-09-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0011_alter_kidsservicessconditions_conditionable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidsservicessconditions',
            name='conditionLimit',
            field=models.IntegerField(null=True),
        ),
    ]
