# Generated by Django 4.2.7 on 2025-09-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0012_alter_kidsservicessconditions_conditionlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidsservicessconditions',
            name='conditionLimit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
