# Generated by Django 4.2.7 on 2025-09-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findservice', '0014_alter_kidsservicessconditions_conditionadd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsservicessconditions',
            name='onlineAble',
            field=models.BooleanField(default=False),
        ),
    ]
